### PR TITLE
Add new starter template

### PR DESCRIPTION
**Pull request by QuackMartins**

### CODE REVIEW

**Comment by QuackMartins** [comment]
Fair enough... I just finished tests implementation, I think by the weekend it will be working entirely

**Comment by web-padawan** [comment]
@QuackMartins are you still working on this starter? There are some TODOs in your readme and it is not clear to me if you consider it ready or not.

**Comment by QuackMartins** [comment]
Hey Mr...

I intend to finish it after 1.0 release, for organization purposes I think
it's better for us to close the Pr

I don't mind opening it again once a really finish the project

o/

**Comment by web-padawan** [comment]
@QuackMartins thanks for the update! Agree that it makes sense to wait for stable release to come.
I'm closing this PR but hopefully we will add your starter template to this list later on.

**Pull request closed without merging**
